services:
  frontend.dev:
    image: node:22
    container_name: nodenest.frontend.dev
    working_dir: /app
    volumes:
      - .:/app
    user: "1000:1000"
    ports:
      - "3000:3000"
    tty: true
    profiles:
      - dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodenest.frontend
    ports:
      - "80:80"
    restart: "unless-stopped"
    profiles:
      - prod
